################################################################################
# This workflow will do a clean install of node dependencies, build the source
# code and run tests across different versions of node.
#
# For more information see:
#
#   https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
#
# This workflow uses the following GitHub Actions secrets:
#
#   * INFURA_API_KEY: Your API key for Infura. Obtain one at https://infura.io/
#
################################################################################

name: Node.js CI

# Controls when the action will run. Triggers the workflow on push or pull
# request events
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in
# parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-18.04
            node-version: 14
          - os: ubuntu-20.04
            node-version: 16

    # Steps represent a sequence of tasks that will be executed as part of the
    # job
    steps:
      - name: Build environment information
        run: 'echo "Matrix OS: ${{ matrix.os }} on $HOSTNAME with $(getconf _NPROCESSORS_ONLN) cores"'

        # Check-out the repository under $GITHUB_WORKSPACE, so the job can
        # access it
      - name: Checkout main repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restore node modules
        id: restore-node
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: npm-install-${{ matrix.os }}-${{ matrix.node-version }}-${{ hashFiles('package.json', 'yarn.lock', 'tools/patch-depends.sh', 'tools/depends/npm/**') }}

      - name: Restore smart contract dependencies
        id: restore-contracts
        uses: actions/cache@v2
        with:
          path: |
            contracts/bytecode
            contracts/depends
            depends
          key: restore-contracts-${{ hashFiles('tools/build-depends.sh', 'tools/depends/chain/**') }}

      - name: Restore Vyper compilers
        id: restore-vyper
        if: steps.restore-contracts.outputs.cache-hit != 'true'
        uses: actions/cache@v2
        with:
          path: |
            ~/.vvm
          key: restore-vyper-${{ hashFiles('tools/depends/chain/curve-contracts/**') }}
          restore-keys: |
            restore-vyper-

      - name: Restore Solidity compilers for Vyper
        id: restore-solcx
        if: steps.restore-contracts.outputs.cache-hit != 'true'
        uses: actions/cache@v2
        with:
          path: |
            ~/.solcx
          key: restore-solcx-${{ hashFiles('tools/depends/chain/curve-contracts/**') }}
          restore-keys: |
            restore-solcx-

      - name: Restore Curve build files
        id: restore-curve
        if: steps.restore-contracts.outputs.cache-hit != 'true'
        uses: actions/cache@v2
        with:
          path: |
            tools/repos/curve-contracts
          key: restore-curve-${{ hashFiles('tools/depends/chain/curve-contracts/**') }}

      - name: yarn install
        if: steps.restore-node.outputs.cache-hit != 'true'
        run: yarn install

      - name: yarn audit-ci
        run: yarn audit-ci

      - name: Build smart contract dependencies
        if: steps.restore-contracts.outputs.cache-hit != 'true'
        run: yarn depends

      - name: yarn lint
        run: yarn lint

      - name: yarn compile
        run: yarn compile

      - name: yarn hardhat:deploy
        run: yarn hardhat:deploy

      - name: yarn test
        run: yarn test
        env:
          CI_INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}

      - name: yarn build
        run: yarn build
